### PR TITLE
[Feature Request] add months in NumTimeExtension #24

### PR DESCRIPTION
**Pull request by shinriyo**
Detail for [Feature Request] add months in NumTimeExtension #24

### CODE REVIEW

**Comment by shinriyo** [comment]
@jogboms
Please review.

**Comment by shinriyo** [comment]
@jogboms 

Hello. I'm sorry. I didn't understand by my English skill.

> I still have some reservations about the issue itself, but after working on this solution, how useful 

What reservations do you have?
Do you need more features about the Issue?

>  scale of 1 - 10.

What does `1 - 10` mean?

**Comment by jogboms** [comment]
Oh sorry. I meant how useful do you think the feature request is to the larger audience if you had to pick from between 1 - 10. I like the feature but afraid it might just end up being bloat in the long run.

**Comment by jogboms** [comment]
Hey @shinriyo 
Did you delete you fork for this change?

**Comment by shinriyo** [comment]
@jogboms I forgot to delete old repository or not.
I might delete for clearing.

**Comment by shinriyo** [comment]
I can see the commit hash number.
https://github.com/jogboms/time.dart/pull/26/commits

but, I can't restore.
```
git checkout -b c2658f5c68cd3425f8dca18014d4688ed76e1252 feature/#24
```

**Comment by shinriyo** [comment]
do you know now to restore?
```
git remote add upstream https://github.com/jogboms/time.dart/
git fetch upstream
```

**Comment by shinriyo** [comment]
I had a local branch.
I pushed again.
[Feature Request] add months in NumTimeExtension #24 #33

**Comment by shinriyo** [comment]
I close it. and use new one.

**Pull request closed without merging**
